# Generated by Django 4.0.5 on 2022-06-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_question',
            name='title',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='category',
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='question',
            field=models.CharField(default='what is react', max_length=255, verbose_name='Question'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Quiz_Name',
        ),
    ]
